services:
  3dmodelcrophealth:
    image: agrorisk:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    env_file:
      - .env
